### PR TITLE
update website v1.6 - update get started page version dropdown

### PR DESCRIPTION
**Pull request by ys2843**
Resolved https://github.com/apache/incubator-mxnet/pull/18238, please verify the change on version 1.6 get started page, tested the drop down. Please let me know if there is any problem. Thanks for reveiwing!

### Comments
+ preview - http://ec2-34-219-134-42.us-west-2.compute.amazonaws.com/

### CODE REVIEW

**Comment by ChaiBapchya** [comment]
Same story here
http://ec2-34-219-59-203.us-west-2.compute.amazonaws.com/versions/1.6/api/python/docs/api/optimizer/index.html

and then switching to any other version [e.g. master/1.5/1.4/... ] redirects to landing page

**Comment by connorgoggins** [comment]
@ChaiBapchya are you referring to the general website version dropdown? This fix is for the Get Started page dropdown, and the behavior you described is the same in the current production website.

Just wanted to clarify in case I'm missing something, did you see any issues with the Get Started dropdown fix? It looks fine to me.

**Comment by ys2843** [comment]
New preview link updated for today, please feel free to verify the change. Thanks

**Comment by ChaiBapchya** [comment]
@connorgoggins Thanks for clarifying. So this is only for "Get started" page.
But even then with 
Screen Shot 2020-05-06 at 10 09 37 AM
Clicking on any other version directs to the landing page.Is this expected?

**Comment by connorgoggins** [comment]
@ChaiBapchya for the general version dropdown, yes, that is expected behavior. This fix is for the version selector dropdown on the Get Started page, not the general version dropdown:
Screen Shot 2020-05-06 at 10 31 39 AM

**Comment by ChaiBapchya** [comment]
Thanks for clarifying. LGTM then!

**Review by connorgoggins — APPROVED** [review]
Great work! Thanks for your contribution :)

**Pull request merged**
